{% set version = "1.4.0" %}

package:
  name: pyproject-api
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproject-api/pyproject_api-{{ version }}.tar.gz
  sha256: ac85c1f82e0291dbae5a7739dbb9a990e11ee4034c9b5599ea714f07a24ecd71

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - hatch-vcs >=0.2
    - hatchling >=1.11.1
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - packaging >=21.3
    - tomli >=2.0.1

test:
  source_files:
    - tests
  imports:
    - pyproject_api
  commands:
    - pip check
    - pytest -vv --cov=pyproject_api --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=76
  requires:
    - pip
    - pytest-cov
    - pytest-mock
    - virtualenv

about:
  home: https://pypi.org/project/pyproject-api
  summary: API to interact with the python pyproject.toml based projects
  dev_url: https://github.com/tox-dev/pyproject-api
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
