{% set version = "1.7.2" %}

package:
  name: pyproject-api
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproject-api/pyproject_api-{{ version }}.tar.gz
  sha256: dc5b0e0f6e291a4f22b46e182c9c6d4915c62b1f089b8de1b73f2d06ae453593

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - hatch-vcs >=0.4
    - hatchling >=1.25
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - packaging >=24.1
    - tomli >=2.0.1

test:
  source_files:
    - tests
  imports:
    - pyproject_api
  commands:
    - pip check
    - coverage run -m --source pyproject_api --branch -m pytest -vv --color=yes --tb=long -k "not setuptools_prepare_metadata_for_build_wheel"
    - coverage report --show-missing --skip-covered --fail-under=76
  requires:
    - coverage
    - pip
    - pytest
    - pytest-mock
    - virtualenv

about:
  home: https://pypi.org/project/pyproject-api
  summary: API to interact with the python pyproject.toml based projects
  dev_url: https://github.com/tox-dev/pyproject-api
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
