{% set version = "1.5.2" %}

package:
  name: pyproject-api
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproject-api/pyproject_api-{{ version }}.tar.gz
  sha256: 999f58fa3c92b23ebd31a6bad5d1f87d456744d75e05391be7f5c729015d3d91

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - hatch-vcs >=0.3
    - hatchling >=1.12.2
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - packaging >=23
    - tomli >=2.0.1

test:
  source_files:
    - tests
  imports:
    - pyproject_api
  commands:
    - pip check
    - pytest -vv --cov=pyproject_api --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=76
  requires:
    - pip
    - pytest-cov
    - pytest-mock
    - virtualenv

about:
  home: https://pypi.org/project/pyproject-api
  summary: API to interact with the python pyproject.toml based projects
  dev_url: https://github.com/tox-dev/pyproject-api
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
